version: '3.1'

services:
  test:
    build: .
    environment:
      - "POSTGRES_PASSWORD=threads"
      - "POSTGRES_USER=sentry"
      - "SENTRY_SECRET_KEY=qy*d@&%^^*5ukn%23b6z8udcg4&&o9#668=%1qpxy-8txg@vm4"
    links:
      - pgsql
      - redis
      - sentry
    command: bash -c "pip install -r requirements_dev.txt && invoke lint test"
  pgsql:
    image: postgres
  redis:
    image: redis:3.2-alpine
  sentry:
    image: sentry
